layout_spectrum: 1
typography_spectrum: 0.9139785
color:
  saturation: 0.7992831
  lightness: 0.3637993
  brandStrength: 0.04442906
  rhythmicContrast: 0.7114695
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
name: jackkitchen
